### ISSUE TITLE
cannot import name 'batched_nms'

### ISSUE THREAD

**Issue by sourabhyadav** [zhiqwang/yolov5-rt-stack#72]
## 🐛 Bug
Following is the error message when I use ```from yolort.models import yolov5s```  
  ```
File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/box_head.py", line 6, in <module>
    from torchvision.ops import batched_nms
ImportError: cannot import name 'batched_nms'
```  

## To Reproduce (REQUIRED)
**Installation:**
```pip3 install -e . ```  

**Run:**  
```
python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from yolort.models import yolov5s
```
**Below is the error:**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/__init__.py", line 3, in <module>
    from yolort import models
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/__init__.py", line 5, in <module>
    from .yolo_module import YOLOModule
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/yolo_module.py", line 9, in <module>
    from . import yolo
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/yolo.py", line 12, in <module>
    from .box_head import YoloHead, SetCriterion, PostProcess
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/box_head.py", line 6, in <module>
    from torchvision.ops import batched_nms
ImportError: cannot import name 'batched_nms'

```

## Environment
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.20200828-gc268e26

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: Quadro P2000

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-lightning==1.1.8
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

Kindly guide for the same.

**Comment by zhiqwang** [comment]
Hi @sourabhyadav 

Thank you for providing such detailed information.

This is because we use some features of torch 1.7.0+ and torchvision 0.8.1+,  so we recommend that you upgrade PyTorch and TorchVision to the [stable](https://pytorch.org/get-started/locally/) version of torch and torchvision.

**Comment by sourabhyadav** [comment]
> Hi @sourabhyadav
> 
> Thank you for providing such detailed information.
> 
> This is because we use some features of torch 1.7.0+ and torchvision 0.8.1+, we recommend that you upgrade PyTorch and TorchVision to the [stable version](https://pytorch.org/get-started/locally/).

@zhiqwang  Thanks.
It worked with updated ```torchvision==0.8.0``` and ```torch==1.7.0``` versions.  


Is is possible to make it work on ```torchvision==0.7.0``` and ```torch==1.6.0``` since our production environment is deployed on these versions?

**Comment by sourabhyadav** [comment]
Yeah it did not work. Following is the error:  

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/__init__.py", line 3, in <module>
    from yolort import models
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/__init__.py", line 5, in <module>
    from .yolo_module import YOLOModule
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/yolo_module.py", line 9, in <module>
    from . import yolo
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/yolo.py", line 12, in <module>
    from .box_head import YoloHead, SetCriterion, PostProcess
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/box_head.py", line 9, in <module>
    from . import _utils as det_utils
  File "/data/sourabh/Play_n_n_Learn/CV_DL/yolov5_exp/yolov5-rt-stack/yolort/models/_utils.py", line 8, in <module>
    from torchvision.ops.boxes import box_convert
ImportError: cannot import name 'box_convert'
```  
Anyways thanks for now.
